Application/Client/Controllers/CustomerController.cs
using API.Models;
using API.Models.VM;
using Client.Repositories.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize]
    public class CustomerController : BaseController<Ticket, TicketRepository, string>
    {
        private readonly TicketRepository _ticketRepos;
        public CustomerController(TicketRepository ticketRepos) : base(ticketRepos)
        {
            this._ticketRepos = ticketRepos;
        }

        [HttpPost]
        public async Task<JsonResult> RequestTicket(RequestTicketVM objReq)
        {
            var userId = User.Claims.Where(x => x.Type.Equals("Id")).FirstOrDefault().Value;
            var userEmail = User.Claims.Where(x => x.Type.Equals("Email")).FirstOrDefault().Value;
            var userPhone = User.Claims.Where(x => x.Type.Equals("Phone")).FirstOrDefault().Value;
            var userName = User.Claims.Where(x => x.Type.Equals("Name")).FirstOrDefault().Value;

            objReq.CustomerID = userId;
            objReq.CustomerEmail = userEmail;
            objReq.CustomerPhone = userPhone;
            objReq.CustomerName = userName;
            objReq.TeamLeadID = "SUPERUSER";

            var objResp = await _ticketRepos.Request(objReq);

            return Json(objResp);
        }

        [HttpPost]
        public async Task<JsonResult> GetMyTickets(TicketOwnerVM objReq)
        {
            var userId = User.Claims.Where(x => x.Type.Equals("Id")).FirstOrDefault().Value;

            objReq.AccountId = userId;

            var objResp = await _ticketRepos.GetMyTickets(objReq);

            return Json(objResp);
        }

        [HttpPost]
        public async Task<JsonResult> GetTicketDetails(RequestTicketDetailVM objReq)
        {
            var objResp = await _ticketRepos.GetTicketDetails(objReq);

            return Json(objResp);
        }

        [HttpGet]
        public async Task<JsonResult> GetAllTickets()
        {
            var result = await _ticketRepos.GetAllTickets();
            return Json(result);
        }

        [HttpPost]
        public async Task<JsonResult> GetAllTicketsByFilter(TicketFilterVM objReq)
        {
            var result = await _ticketRepos.GetAllTicketsByFilter(objReq);
            return Json(result);
        }


        [HttpGet]
        public async Task<JsonResult> GetSystemStatistic()
        {
            var result = await _ticketRepos.GetSystemStatistic();
            return Json(result);
        }

        [HttpPost]
        public async Task<JsonResult> GetSubordinateStatistic(TicketOwnerVM objReq)
        {
            var result = await _ticketRepos.GetSubordinateStatistic(objReq);
            return Json(result);
        }

        [HttpPost]
        public async Task<JsonResult> GetPersonalStatistic(TicketOwnerVM objReq)
        {
            var result = await _ticketRepos.GetPersonalStatistic(objReq);
            return Json(result);
        }

        [HttpPut]
        public JsonResult UpdateTicket(UpdateTicketVM ticketVM)
        {
            var result = _ticketRepos.UpdateTicket(ticketVM);
            return Json(result);
        }

        [HttpPut]
        public JsonResult AssignTicket(AssignTicketVM ticketVM)
        {
            var result = _ticketRepos.AssignTicket(ticketVM);
            return Json(result);
        }

        public IActionResult MyTicket()
        {
            return View();
        }
        public IActionResult RequestTicket()
        {
            return View();
        }
        public IActionResult TicketDetails()
        {
            return View();
        }

        public IActionResult SolvedTicket()
        {
            return View();
        }
    }
}

Application/Client/Controllers/TeamLeadController.cs
using API.Models;
using API.Models.VM;
using Client.Repositories.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize(Roles = "Admin,Team Lead")]
    public class TeamLeadController : BaseController<Ticket, TicketRepository, string>
    {
        private readonly TicketRepository _ticketRepos;
        public TeamLeadController(TicketRepository ticketRepos) : base(ticketRepos)
        {
            this._ticketRepos = ticketRepos;
        }

        [HttpPost]
        public async Task<JsonResult> EscalateTicket(AssignTicketVM ticketVM)
        {
            var userId = User.Claims.Where(x => x.Type.Equals("Id")).FirstOrDefault().Value;
            ticketVM.TeamLeadId = userId;
            var objResp = await _ticketRepos.Escalate(ticketVM);
  
            return Json(objResp);
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Assign()
        {
            return View();
        }
    }
}

Application/Client/Views/Shared/ErrorLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Additional CSS -->
    @RenderSection("CSS", required: false)
</head>
<body>
    @RenderBody()

    @RenderSection("Scripts", required: false)
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Application/Client/Views/Shared/LayoutHome.cshtml
<!--
=========================================================
* Argon Dashboard 2 - v2.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/logo-self.png" style="width:10px; height:10px">
    <title>@ViewData["Title"]</title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <!-- Nucleo Icons -->
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link id="pagestyle" href="~/assets/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
    <!-- Additional CSS -->
    @RenderSection("CSS", required: false)
</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0" asp-controller="Home" asp-action="Test">
                <img src="~/assets/img/logo-self.png" class="navbar-brand-img h-100" alt="main_logo">
                <span class="ms-1 font-weight-bold">ʜᴀᴅᴇꜱ</span>
                <p><span class="ms-1 font-weight-bold">ʜᴀʟᴘ ᴅᴇꜱᴋ ꜱʏꜱᴛᴇᴍ <small>v0.01</small></span></p>
            </a>
        </div>
        <hr class="horizontal dark mt-0">
        <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
            <ul class="navbar-nav">
                @if (User.IsInRole("Team Lead") || User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                        <a class="nav-link active" asp-controller="Admin" asp-action="Assign">
                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                            </div>
                            <span class="nav-link-text ms-1">Assign Tickets</span>
                        </a>
                        }
                        else { 
                        <a class="nav-link active" asp-controller="TeamLead" asp-action="Assign">
                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                            </div>
                            <span class="nav-link-text ms-1">Assign Tickets</span>
                        </a>
                        }
                    </li>

                }
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Customer" asp-action="MyTicket">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">My Tickets</span>
                    </a>
                </li>
                @if (User.IsInRole("Customer"))
                {
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Customer" asp-action="RequestTicket">
                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                            </div>
                            <span class="nav-link-text ms-1">Request Tickets</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Customer" asp-action="SolvedTicket">
                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                            </div>
                            <span class="nav-link-text ms-1">Solved Tickets</span>
                        </a>
                    </li>
                }

                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link " asp-controller="Admin" asp-action="Register">
                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                            </div>
                            <span class="nav-link-text ms-1">Add User</span>
                        </a>
                    </li>
                }

            </ul>
        </div>
    </aside>
    <main class="main-content position-relative border-radius-lg ">
        <!-- Navbar -->
        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
            <div class="container-fluid py-1 px-3">
                <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                    <ul class="navbar-nav  justify-content-end">
                        <li class="nav-item d-flex align-items-center">
                            <a class="nav-link text-white font-weight-bold px-0" asp-controller="Login" asp-action="Logout">
                                <i class="fa fa-user me-sm-1"></i>
                                <span class="d-sm-inline d-none">Log Out</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->
        <div class="container-fluid py-4">
            @RenderBody()
        </div>
    </main>
    <!--   Core JS Files   -->
    <!-- Additional Scripts -->
    @RenderSection("Scripts", required: false)
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/chartjs.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        var ctx1 = document.getElementById("chart-line").getContext("2d");

        var gradientStroke1 = ctx1.createLinearGradient(0, 230, 0, 50);

        gradientStroke1.addColorStop(1, 'rgba(94, 114, 228, 0.2)');
        gradientStroke1.addColorStop(0.2, 'rgba(94, 114, 228, 0.0)');
        gradientStroke1.addColorStop(0, 'rgba(94, 114, 228, 0)');
        new Chart(ctx1, {
            type: "line",
            data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                    label: "Mobile apps",
                    tension: 0.4,
                    borderWidth: 0,
                    pointRadius: 0,
                    borderColor: "#5e72e4",
                    backgroundColor: gradientStroke1,
                    borderWidth: 3,
                    fill: true,
                    data: [50, 40, 300, 220, 500, 250, 400, 230, 500],
                    maxBarThickness: 6

                }],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            padding: 10,
                            color: '#fbfbfb',
                            font: {
                                size: 11,
                                family: "Open Sans",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: false,
                            drawOnChartArea: false,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            color: '#ccc',
                            padding: 20,
                            font: {
                                size: 11,
                                family: "Open Sans",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });</script>
    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }</script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/assets/js/argon-dashboard.min.js?v=2.0.4"></script>
</body>

</html>

Application/Client/Views/Shared/LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Additional CSS -->
    @RenderSection("CSS", required: false)
</head>
<body>
    @RenderBody()
    <!-- Additional Scripts -->
    @RenderSection("Scripts", required: false)
    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

Application/Client/Views/Shared/LayoutRequest.cshtml
<!--
=========================================================
* Argon Dashboard 2 - v2.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/logo-self.png" style="width:10px; height:10px">
    <title>@ViewData["Title"]</title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <!-- Nucleo Icons -->
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link id="pagestyle" href="~/assets/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
    <!-- Additional CSS -->
    @RenderSection("CSS", required: false)
</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0" asp-controller="Home" asp-action="Test">
                <img src="~/assets/img/logo-self.png" class="navbar-brand-img h-100" alt="main_logo">
                <span class="ms-1 font-weight-bold">ʜᴀᴅᴇꜱ</span>
                <p><span class="ms-1 font-weight-bold">ʜᴀʟᴘ ᴅᴇꜱᴋ ꜱʏꜱᴛᴇᴍ <small>v0.01</small></span></p>
            </a>
        </div>
        <hr class="horizontal dark mt-0">
        <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
            <ul class="navbar-nav">
                @if (User.IsInRole("Team Lead") || User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link active" asp-controller="Admin" asp-action="Assign">
                                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                    <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                                </div>
                                <span class="nav-link-text ms-1">Assign Tickets</span>
                            </a>
                        }
                        else
                        {
                            <a class="nav-link active" asp-controller="TeamLead" asp-action="Assign">
                                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                    <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                                </div>
                                <span class="nav-link-text ms-1">Assign Tickets</span>
                            </a>
                        }
                    </li>

                }
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="Customer" asp-action="MyTicket">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">My Tickets</span>
                    </a>
                </li>
                @if (User.IsInRole("Customer"))
                {
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Customer" asp-action="RequestTicket">
                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                            </div>
                            <span class="nav-link-text ms-1">Request Tickets</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Customer" asp-action="SolvedTicket">
                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                            </div>
                            <span class="nav-link-text ms-1">Solved Tickets</span>
                        </a>
                    </li>
                }

                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link " asp-controller="Admin" asp-action="Register">
                            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                            </div>
                            <span class="nav-link-text ms-1">Add User</span>
                        </a>
                    </li>
                }

            </ul>
        </div>
    </aside>
    <main class="main-content position-relative border-radius-lg ">
        <!-- Navbar -->
        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
            <div class="container-fluid py-1 px-3">
                <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                    <ul class="navbar-nav  justify-content-end">
                        <li class="nav-item d-flex align-items-center">
                            <a class="nav-link text-white font-weight-bold px-0" asp-controller="Login" asp-action="Logout">
                                <i class="fa fa-user me-sm-1"></i>
                                <span class="d-sm-inline d-none">Log Out</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->
        <div class="container-fluid py-4">
            @RenderBody()
        </div>
    </main>
    <!--   Core JS Files   -->
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/chartjs.min.js"></script>
    <!-- Additional Scripts -->
    @RenderSection("Scripts", required: false)
    <script>
    var ctx1 = document.getElementById("chart-line").getContext("2d");

        var gradientStroke1 = ctx1.createLinearGradient(0, 230, 0, 50);

        gradientStroke1.addColorStop(1, 'rgba(94, 114, 228, 0.2)');
        gradientStroke1.addColorStop(0.2, 'rgba(94, 114, 228, 0.0)');
        gradientStroke1.addColorStop(0, 'rgba(94, 114, 228, 0)');
        new Chart(ctx1, {
            type: "line",
            data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                    label: "Mobile apps",
                    tension: 0.4,
                    borderWidth: 0,
                    pointRadius: 0,
                    borderColor: "#5e72e4",
                    backgroundColor: gradientStroke1,
                    borderWidth: 3,
                    fill: true,
                    data: [50, 40, 300, 220, 500, 250, 400, 230, 500],
                    maxBarThickness: 6

                }],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            padding: 10,
                            color: '#fbfbfb',
                            font: {
                                size: 11,
                                family: "Open Sans",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: false,
                            drawOnChartArea: false,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            color: '#ccc',
                            padding: 20,
                            font: {
                                size: 11,
                                family: "Open Sans",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });</script>
    <script>
    var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }</script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/assets/js/argon-dashboard.min.js?v=2.0.4"></script>
</body>

</html>

Application/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>